# Dockerfile.dev

FROM node:20-alpine

RUN mkdir -p /app/frontend

WORKDIR /app/frontend

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]