# Dockerfile.prod

FROM node:20-alpine

WORKDIR /app/backend

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

COPY . . 

RUN pnpm run build

CMD ["node", "dist/main.js"]